virtualMachinesCoreOs:
  hosts:      
   fcos-test-01:
     ansible_host: 192.168.122.105
  vars:
    successMessage: "installed tree binary on all Fedora CoreOS hosts"

virtualMachinesUbuntu:
  hosts:
    ubuntu-01:
      ansible_host: 192.168.122.233
  vars:
    successMessage: "installed tree binary on all Ubuntu hosts"