virtualMachinesCoreOs:
  hosts:      
   fcos-test-01:
     ansible_host: 192.168.122.105
  vars:
    successMessage: "installed tree binary on Fedora CoreOS host"

virtualMachinesUbuntu:
  hosts:
    ubuntu-01:
      ansible_host: 192.168.122.233
  vars:
    successMessage: "installed tree binary on  Ubuntu host"