virtualMachinesCoreOs:
  hosts:      
   coreos-01:
     ansible_host: 192.168.122.52
   coreos-02:
     ansible_host: 192.168.122.64
   coreos-03:
     ansible_host: 192.168.122.95

  vars:
    successMessageInstall: "installed tree binary on Fedora CoreOS host"
    successMessageUninstall: "uninstalled tree binary on Fedora CoreOS host"

virtualMachinesUbuntu:
  hosts:
    ubuntu-01:
      ansible_host: 192.168.122.215
    ubuntu-02:
      ansible_host: 192.168.122.249
    ubuntu-03:
      ansible_host: 192.168.122.156

  vars:
    successMessageInstall: "installed tree binary on Ubuntu host"
    successMessageUninstall: "uninstalled tree binary on Ubuntu host"

all:    
  vars:
    key1: "value1"
    key2: "value2" 
    operation: present
