- name: Install tree fs utility and reboot system
  hosts: virtualMachines
  become: true
  tasks:
          ##   - name: Install yum package manager
          ##     community.general.rpm_ostree_pkg:
          ##       name: yum
          ##       state: present

   - name: Install tree package
     yum:
       name: tree
       state: latest
       use_backend: yum4

   - name: reboot the machine
     ansible.builtin.reboot:
    
