- name: Install tree fs utility on CoreOs machines and reboot system
  hosts: virtualMachinesCoreOs
  become: true
  tasks:
   - name: Install tree fs utility
     community.general.rpm_ostree_pkg:
       name: tree
       state: present

   - name: reboot the machine
     ansible.builtin.reboot:

   - name: Print success Message
     ansible.builtin.debug:
       msg: "Successfully {{ successMessage }}"

- name: Install tree fs utility on ubuntu machines
  hosts: virtualMachinesUbuntu
  become: true
  tasks:
    - name: Install tree fs utility
      ansible.builtin.apt:
        name: tree
        state: present
    - name: Print success Message
      ansible.builtin.debug:
        msg: "Successfully {{ successMessage }}"
