- name: Install/Uninstall tree fs utility on CoreOs machines and reboot system
  hosts: virtualMachinesCoreOs
  become: true
  tasks:
   - name: Install/Uninstall tree fs utility
     community.general.rpm_ostree_pkg:
       name: tree
       state: "{{ operation }}"

   - name: reboot the machine
     ansible.builtin.reboot:

   - name: Print success Message Install
     ansible.builtin.debug:
#       var: ansible_facts
       msg: "Successfully {{ successMessageInstall }} - {{ ansible_nodename }}, with IP Address: {{ ansible_facts['all_ipv4_addresses'] }} "
     when: operation == "present"

   - name: Print success Message Uninstall
     ansible.builtin.debug:
#       var: ansible_facts
       msg: "Successfully {{ successMessageUninstall }} - {{ ansible_nodename }}, with IP Address: {{ ansible_facts['all_ipv4_addresses'] }} "
     when: operation == "absent"


- name: Install/Uninstall tree fs utility on ubuntu machines
  hosts: virtualMachinesUbuntu
  become: true
  tasks:
    - name: Install/Uninstall tree fs utility
      ansible.builtin.apt:
        name: tree
        state: "{{ operation }}"
    - name: Print success Message
      ansible.builtin.debug:
#        var: ansible_facts
        msg: "Successfully {{ successMessageInstall }} - {{ ansible_nodename }}, with IP Address: {{ ansible_facts['all_ipv4_addresses'] }}  "
      when: operation == "present"

    - name: Print success Message Uninstall
      ansible.builtin.debug:
        msg: "Successfully {{ successMessageUninstall }} - {{ ansible_nodename }}, with IP Address: {{ ansible_facts['all_ipv4_addresses'] }}  "
      when: operation == "absent"

