virtualMachinesCoreOs:
  hosts:      
   coreos-01:
     ansible_host: 192.168.122.52
   coreos-02:
     ansible_host: 192.168.122.64
   coreos-03:
     ansible_host: 192.168.122.95

  vars:
    successMessage: "installed tree binary on Fedora CoreOS host"

virtualMachinesUbuntu:
  hosts:
    ubuntu-01:
      ansible_host: 192.168.122.233
      key1: "value1-host-1"
    ubuntu-02:
      ansible_host: 192.168.122.85
      key1: "value1-host-2"
    ubuntu-03:
      ansible_host: 192.168.122.245

  vars:
    successMessage: "installed tree binary on  Ubuntu host"
    key1: "value1-group"

all:
  vars:
   myKeys:      
     key1: "value1-all-old"
     key2: "value2" 

