- hosts: localhost
  become: false
  tasks:
    - name: stop lxc Containers (k8s nodes)
      lxd_container:
        name: "{{ item }}"
        state: stopped
        force_stop: true
        timeout: 45
      loop:
        - "kmaster"
        - "kworker1"
        - "kworker2"
        - "kworker3"

    - name: delete lxc Containers (k8s nodes)
      lxd_container:
        name: "{{ item }}"
        state: absent
      loop:
        - "kmaster"
        - "kworker1"
        - "kworker2"
        - "kworker3"

