---
# tasks file for install-k8s

- name: Verify that all needed ports are opened
  shell: |
    nc -l 127.0.0.1 {{ item }} & \
    sleep 0.05
    nc -zv 127.0.0.1 {{ item }}
  register: result
  loop:
    - 6443
    - 2379
    - 2380
    - 10250
    - 10259
    - 10257



