---
# tasks file for install-k8s

- name: Verify that all needed ports are opened
  shell: |
    nc -l 127.0.0.1 {{ item }} & \
    nc -zv 127.0.0.1 {{ item }}
  register: result
  failed_when: result.rc not in [ 0, 1 ]
  loop:
    - 6443
    - 2379
    - 2380
    - 10250
    - 10259
    - 10257



